spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/talklife_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174
app.ai.ollama.base-url=http://localhost:11434
app.ai.ollama.model=translategemma:latest
